config/routes.rb
Rails.application.routes.draw do
  
  resources :tipp_groups do
    member do
     post 'create_member'
     delete 'delete_member'
    end
  end
  get 'rankings/overall/:id', to: 'rankings#overall', as: :rankings_overall_show
  get 'rankings/tipp_group/:id', to: 'rankings#tipp_group', as: :rankings_tipp_group_show
  get 'rankings/matchday/:id', to: 'rankings#matchday', as: :rankings_matchday_show

  get 'regeln', to: 'static_pages#rules', as: :rules
  get 'home', to: 'static_pages#home', as: :home

  get 'tipps', to: 'tipps#index', as: :tipps_index
  get 'tipps/:id', to:'tipps#edit', as: :edit_tipp
  post 'tipps', to:'tipps#create', as: :tipps

  devise_for :users

  root 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def rules
  end

  def home
    matches = Match.all
    matches.each do |match|
      if DateTime.now < match.match_time
        @matchday = match.matchday
        break
      end
    end
    @matches = Match.where(matchday: @matchday)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_login_form.erb
<% unless current_user %>
  <div class="col-md-4">
    <div class="well">
      <h2 class="h2">Einloggen</h2>
      <%= form_for(:user, :url => session_path(:user), html: { role: "form"}) do |f| %>
        <div class="form-group"><%= f.label :email, "E-Mail-Adresse" %><br />
        <%= f.email_field :email, autofocus: true, class:"form-control" %></div>

        <div class="form-group"><%= f.label :password, "Passwort" %><br />
          <%= f.password_field :password, autocomplete: "off", class:"form-control" %></div>

        <% if devise_mapping.rememberable? -%>
          <div class="form-group"><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
        <% end -%>

        <div><%= f.submit "Einloggen", class: "btn btn-primary active" %></div>
      <% end %>
    </div>
  </div>

<% else %>
  <div class="col-md-4">
    <div class="panel panel-primary">
    <div class="panel-heading">Hallo <%= current_user.username %></div>
    <div class="panel-body">
      <p>Sie liegen im Moment auf dem <%= current_user.rank %>. Platz der Gesamtwertung.</p>
      <p>Sie haben bisher <%= current_user.points %> Punkte erreicht.</p>
      <%= link_to "Jetzt tippen!", edit_tipp_path(@matchday), class:"btn btn-primary btn-lg btn-block active" %>
    </div>
  </div>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div  class="col-md-8">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value.html_safe, class: "alert alert-warning", role: "alert" %>
  <% end %>
  <div class="panel panel-primary">
    <div class="panel-heading">Tippspiel zur Bundesliga-Saison 2014/2015</div>
    <div class="panel-body">
      <p>Fußballexperte? Sie wissen alles besser? Zeigen Sie es. <br>Tippen Sie mit!<br>
      </p>
      <p>Einfach registrieren und mittippen und einen von vielen tollen Preisen gewinnen!</p>
    </div>
  </div>

  <div class="panel panel-primary">
    <div class="panel-heading">Die nächsten Spiele:</div>
    <table class="table table-striped">
      <thead>
          
      </thead>
      <tbody>
        <% @matches.each do |match| %>
          <tr>
            <td class="align-center cell-sm" >
              <%= match.match_time.in_time_zone("CET").strftime("%d.%m, %H:%M")  %>
            </td>
            <td class="align-right cell-md"><%= match.home_team %></td>
            <td class="align-center cell-xs">:</td>  
            <td class="align-left cell-md"><%= match.away_team %></td>
            <td class="align-center cell-sm"><%=link_to "Jetzt tippen!", edit_tipp_path(@matchday), class: "badge alert-info" %></td>
          </tr>
        <% end %>       
      </tbody>
    </table>  
  </div>
</div>
<%= render 'static_pages/login_form' %>

app/views/static_pages/rules.html.erb
<div class="col-md-12">
  <div class="well">
    <h2>REGELN / HILFE</h2>
    <div class="panel panel-primary">
    <div class="panel-heading"><h4>Wertung</h4></div>
    <div class="panel-body">
      <p><b>Wie wird gewertet?</b></p>
      <ul>
        <li>Ergebnis richtig : 3 Punkte</li>
        <li>Tordifferenz richtig : 2 Punkte</li>
        <li>Tendenz richtig (Sieg, Unentschieden, Niederlage): 1 Punkt</li>
        <li>Ergebnis und Tendenz falsch : 0 Punkte</li>
      </ul>

      <p><b>Beispiel:</b></p>

        FC Schalke 04 gewinnt gegen Bayern München 2:1. <br>
        <ul>
          <li>Der Tipp 2:1 bringt volle 3 Punkte</li>
          <li>die Tipps 3:2, 1:0, ... 2 Punkte</li>
          <li>der Tipp 2:0 noch 1 Punkt</li>
          <li>für ein 1:1 oder ein 1:2 würden keine Punkte vergeben</li>
        </ul>
      
      <p>
        <b>Wann wird gewertet?</b><br>
        Bis kurz vor dem vor Anpfiff können Sie noch Ihre Tipps abgeben und überarbeiten. Am Ende der Tipprunde werden die Ergebnisse gewertet und die Ranglisten aktualisiert.
      </p>
    </div>
  </div>

<div class="panel panel-primary">
    <div class="panel-heading"><h4>Tipp-Gruppe</h4></div>
    <div class="panel-body">
      <p><b>Erklärung</b></p>

      <p>In einer Tipp-Gruppe gehen dann nur die Punkte der Mitglieder in die Tipp-Gruppen-Wertung ein. Kämpft gegeneinander um die Punkte! <br>Gründen Sie selbst ein Tipp-Gruppe oder treten Sie dem Tipp-Gruppe Ihrer Freunde bei. <br>Sorgen Sie mit einem Passwort dafür, dass nur Ihre Freunde Ihrer Tipp-Gruppe beitreten. <br>Ein Tipp-Gruppe reicht Ihnen nicht? - Kein Problem, denn Sie können an mehreren Ligen teilnehmen. <br>Erfahren Sie in den Tipp-Gruppe-Ranglisten, wie gut Sie wirklich sind.
      </p>
      <p>
        <b>Wie wird gewertet?</b><br>
        Die Rangliste eines Tipp-Gruppe erfolgt durch Vergleich der Punkte der einzelnen Mitglieder. 
        Einsehbar auf den Ranglisten-Seiten. Können Sie Ihre Freunde schlagen?
      </p>
    </div>
  </div>


<div class="panel panel-primary">
    <div class="panel-heading"><h4>Ranglisten</h4></div>
    <div class="panel-body">
      <p><b>Gesamtwertung</b></p>

      <p>Übersicht der erfolgreichsten Spieler aller bisherigen Spieltage.<br>
      </p>
      <p><b>Tipp-Gruppe Saison</b></p>
      <p>Rangliste für die Tipp-Gruppe, denen Sie beigetreten sind.</p>
      <p><b>Einzelwertung Spieltag</b></p>
      <p>Übersicht der erfolgreichsten Spieler des ausgewählten Spieltages.</p>
      <p><b>Medaillen</b></p>
      <p>Erläuterung <br>
        Jede Saison erhält jeder Spieler eine Medaille, die sein Abschneiden in dieser Saison widerspiegelt
        Beispiel <br>
        Gold - Hat ersten Platz belegt. <br>
        Silber - Hat den zweiten Platz belegt. <br>
        Bronze - Hat den dritten Platz belegt. <br>
        Top 10 - War unter den ersten 10. <br>
      </p>

    </div>
  </div>

<div class="panel panel-primary">

    <div class="panel-heading">
      <h4>Teilnahmebedingungen</h4>
    </div>
    <div class="panel-body">
      <p>
        <b>Teilnahme- und Gewinnberechtigung</b><br>
            
Teilnahmeberechtigt an dem Gewinnspiel und gewinnberechtigt sind nur natürliche Personen, die durch Zustimmung dieser Teilnahmebedingungen ihre Teilnahme an dem Gewinnspiel erklärt haben. Wer falsche E-Mail-Adressen verwendet oder mehrere Konten führt, wird von Teilnahme und Gewinnspiel ausgeschlossen.
      </p>
        <p><b>Gegenstand, Ablauf und Modus des Gewinnspiels</b><br>
            
Das Gewinnspiel wird anhand der erreichten Tippergebnisse unter allen gewinnberechtigten Teilnehmern des Gewinnspiels ausgewertet. Der Gewinn ist nicht übertragbar. Eine Auszahlung in bar ist ausgeschlossen.
      </p>
        <p><b>Gewinnmitteilung</b><br>
Der Gewinner wird per E-Mail benachrichtigt.
      </p>
        <p><b>Datenschutz</b><br>
            
Die E-Mail-Adresse wird ausschließlich genutzt um den Gewinner benachrichtigen zu können. Ihre personenbezogenen Daten weder entgeltlich noch unentgeltlich an Dritte weitergeben.
      </p>
        <p><b>Rechtsweg</b><br>
            
Der Rechtsweg ist ausgeschlossen.
         
      </p>
    </div>
  </div>

</div>
</div>