config/routes.rb
Rails.application.routes.draw do
  
  resources :tipp_groups do
    member do
     post 'create_member'
     delete 'delete_member'
    end
  end
  get 'rankings/overall/:id', to: 'rankings#overall', as: :rankings_overall_show
  get 'rankings/tipp_group/:id', to: 'rankings#tipp_group', as: :rankings_tipp_group_show
  get 'rankings/matchday/:id', to: 'rankings#matchday', as: :rankings_matchday_show

  get 'regeln', to: 'static_pages#rules', as: :rules
  get 'home', to: 'static_pages#home', as: :home

  get 'tipps', to: 'tipps#index', as: :tipps_index
  get 'tipps/:id', to:'tipps#edit', as: :edit_tipp
  post 'tipps', to:'tipps#create', as: :tipps

  devise_for :users

  root 'static_pages#home'

end

app/models/tipp.rb
class Tipp < ActiveRecord::Base
  belongs_to :user
  belongs_to :match

  validates :home_goals, :numericality => { :greater_than_or_equal_to => 0, 
    :less_than_or_equal_to => 15, 
    :message => "Die Zahl der geschossenen Tore muss zwischen 0 und 15 liegen." }
  validates :away_goals, :numericality => { :greater_than_or_equal_to => 0, 
    :less_than_or_equal_to => 15, 
    :message => "Die Zahl der geschossenen Tore muss zwischen 0 und 15 liegen." }
  validates :home_goals, numericality: { only_integer: true, message: "Bitte nur Zahlen eintragen" }
  validates :away_goals, numericality: { only_integer: true, message: "Bitte nur Zahlen eintragen" }

  validates_presence_of :match_id, :message => "Der Tipp kann keinem Spiel zugeordnet werden."
  validates_presence_of :home_goals, :message => "No Home Goals"
  validates_presence_of :away_goals, :message => "No away Goals"
  validates_presence_of :user_id, :message => "Der Tipp kann keinem Tipper zugeordnet werden. Bitte loggen Sie sich ein."

end

app/controllers/tipps_controller.rb
class TippsController < ApplicationController
  before_action :set_tipp, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /tipps
  # GET /tipps.json
  def index
    matches = Match.all
    matches.each do |match|
      if DateTime.now < match.match_time
        redirect_to edit_tipp_path(match.matchday)
        break
      end
    end
  end

  # GET /tipps/1
  # GET /tipps/1.json
  def show
  end

  # GET /tipps/new
  def new
    
  end

  # GET /tipps/1/edit
  def edit
    @days = %w(So Mo Di Mi Do Fr Sa)

  end

  # POST /tipps
  # POST /tipps.json
  def create
    if current_user
      @formerrors = []
      tipps = params[:tipps]
      p tipps = tipps.values.flatten if tipps.is_a?(Hash)
      p tipps.last
      matchday = Match.find(tipps.last["match_id"]).matchday
      tipps.each do |tipp|
        match_id = tipp["match_id"]
        home_goals = tipp["home_goals"]
        away_goals = tipp["away_goals"]
        @tipp = Tipp.find_or_initialize_by(match_id: match_id, user_id: current_user)
        @tipp.home_goals = home_goals
        @tipp.away_goals = away_goals
        @tipp.user_id = current_user.id

        if check_tipp(tipp)
          @tipp
          @formerrors << @tipp.errors.messages.values unless @tipp.save
        end
       

      end
      @formerrors = create_ul
      redirect_to edit_tipp_path(matchday), notice: @formerrors
    end
  end

  # PATCH/PUT /tipps/1
  # PATCH/PUT /tipps/1.json
  def update
    
  end

  # DELETE /tipps/1
  # DELETE /tipps/1.json
  def destroy
    
  end

  private

    def check_tipp(tipp)
      return false if tipp["home_goals"] == "" or tipp["away_goals"] == "" or !tipp["home_goals"] or !tipp["away_goals"]
      match = Match.find(tipp["match_id"])
      if DateTime.now > match.match_time
        @formerrors << "Für das Spiel #{match.home_team} - #{match.away_team} können keine Tipps mehr abgegeben werden."
        false
      end
      true
    end

    def create_ul 
      return "Ihre Tipps wurden erfolgreich übermittelt." if @formerrors.length == 0
      result = "<ul>"
      @formerrors.flatten().uniq.each do |msg|
        result += "<li>"
        result += msg
        result += "</li>"
      end
      result += "</ul>"
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_tipp
      @matchday = params[:id].to_i
      lastmatch = @matchday * 9
      firstmatch = lastmatch - 8
      @tipps = Tipp.where(user_id: current_user.id).where("match_id <= ? AND match_id >= ?", lastmatch, firstmatch).order(:match_id)
      @user_id = current_user.id
      @matches = Match.where(["matchday = ?", params[:id]]).order(:match_time)
      @top10 = User.limit(10).ordered
      @matchday_top = MatchdayPoint.includes(:user).where(matchday: @matchday).limit(10).ordered
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipp_params
      params.require(:tipps).map do |p|
        p.permit(:home_goals, :away_goals, :user_id, :match_id, :points)
      end
      
    end
end

app/helpers/tipps_helper.rb
module TippsHelper
end

app/views/tipps/_form.html.erb
<%= form_tag tipps_path do %>
  
  <%= hidden_field_tag "matchday", @matchday, { :id => "matchday" } %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th class="align-left" >Datum</th>
        <th class="align-right"></th>

        <th class="align-center" colspan="3">Tipp</th>
        
        <th class="align-left"></th>
        <th class="align-center">Ergebnis</th>
        <th>Punkte</th>
      </tr>
    </thead>
    <tbody>
      <% @matches.each do |match| %>
        <% tipp = Tipp.new %>
        <% tipp_index = @tipps.find_index {|item| item.match_id == match.id} %>
        <% tipp = @tipps[tipp_index] if tipp_index %>

        <%= fields_for "tipps[]", tipp, index: nil do |f| %>
          <tr>
            <%= f.hidden_field :match_id, :value => match.id %>
            <td class="align-left cell-sm" >
              <% day = match.match_time.strftime("%w")%>
              <%= @days[day.to_i] + ". " %>
              <%= match.match_time.in_time_zone("CET").strftime("%d.%m, %H:%M")  %>
            </td>
            <td class="align-right cell-md"><%= match.home_team %></td>

            <% if DateTime.now < match.match_time %>
              <td class="align-right cell-xs"> 
                <%= f.text_field(:home_goals, class: "form-control input-sm",:pattern => '[0-9]{1,2}') %>
              </td>
            <% else %>
              <td class="align-right cell-xs"> <%= f.text_field(:home_goals, class: "form-control input-sm", id:"disabledInput", :disabled => true) %></td>
            <% end %>

            <td class="align-center cell-xs">:</td>
            <% if DateTime.now < match.match_time %>
              <td class="align-left cell-xs"> 
                <%= f.text_field(:away_goals, class: "form-control input-sm",:pattern => '[0-9]{1,2}') %>
              </td>
            <% else %>
              <td class="align-left cell-xs"> <%= f.text_field(:away_goals, class: "form-control input-sm", id:"disabledInput", :disabled => true) %></td>
            <% end %> 
            <td class="align-left cell-md" ><%= match.away_team %></td>
            
            <% if match.home_goals %>
              <td class="align-center cell-sm"><%= match.home_goals %> - <%= match.away_goals %></td>
            <% else %>
              <td class="align-center cell-xs">-</td>
            <% end %>
            <td class="align-center cell-xs"><div class="label label-default"><%= tipp.points  %></div></td>
          </tr>
        <% end %>
      <% end %>
      <tr>
        <td colspan="3">
          <%= submit_tag "Tipps abgeben" , class: "btn btn-primary btn-lg btn-block", role: "button" if DateTime.now < @matches.last.match_time %>
        </td>
        <td colspan="4" class="align-right">Spieltag-Punktzahl:</td>
        <td class="align-center"><div class="label label-default"><%= @tipps.inject(0){|sum,e| sum += e.points if e.points} %></div></td>
      </tr>
    
    </tbody>

  </table>

  
<% end %>

app/views/tipps/edit.html.erb
<div class="col-md-8">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value.html_safe, class: "alert alert-warning", role: "alert" %>
  <% end %>

  <div class="well"> 
    <div class="h4"><%= @matches.first.matchday %>. Spieltag</div>   
    <ul class="pager">
      <% if @matchday > 1 %>
        <li class="previous"><%= link_to "&larr; Voriger Spieltag".html_safe, edit_tipp_path(@matchday - 1) %></li>
      <% else %>
        <li class="previous disabled"><a href="#">&larr; Voriger Spieltag</a></li>
      <% end %>
      
      <% if @matchday < 34 %>
        <li class="next"><%= link_to "Nächster Spieltag &rarr;".html_safe, edit_tipp_path(@matchday + 1) %></li>
      <% else %>
        <li class="next disabled"><a href="#">Nächster Spieltag &rarr;</a></li>
      <% end %>
    </ul>
    <%= render 'form' %>
  </div>
</div>
<div class="col-md-4">  
  <div class="panel panel-primary">
    <div class="panel-heading">Gesamtwertung</div>
    <table class="table">
      <thead>
        <tr>
          <th>Platz</th>
          <th>Name</th>
          <th>Punkte</th>
        </tr>
      </thead>
      <tbody>
        <% @top10.each do |user| %>
          <tr>
            <td><%= user.rank %>.</td>
            <td><%= user.username %></td>
            <td><%= user.points %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="col-md-4">
  <div class="panel panel-primary">
    <div class="panel-heading"><%= @matchday %>. Spieltag <span class="pull-right">Top 10</span></div>
    <table class="table">
      <thead>
        <tr>
          <th>Platz</th>
          <th>Name</th>
          <th>Punkte</th>
        </tr>
      </thead>
      <tbody>
        <% @matchday_top.each_with_index do |entry, index| %>
          <tr>
            <td><%= index + 1 %>.</td>
            <td><%= entry.user.username %></td>
            <td><%= entry.points %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>