config/routes.rb
Rails.application.routes.draw do
  
  resources :tipp_groups do
    member do
     post 'create_member'
     delete 'delete_member'
    end
  end
  get 'rankings/overall/:id', to: 'rankings#overall', as: :rankings_overall_show
  get 'rankings/tipp_group/:id', to: 'rankings#tipp_group', as: :rankings_tipp_group_show
  get 'rankings/matchday/:id', to: 'rankings#matchday', as: :rankings_matchday_show

  get 'regeln', to: 'static_pages#rules', as: :rules
  get 'home', to: 'static_pages#home', as: :home

  get 'tipps', to: 'tipps#index', as: :tipps_index
  get 'tipps/:id', to:'tipps#edit', as: :edit_tipp
  post 'tipps', to:'tipps#create', as: :tipps

  devise_for :users

  root 'static_pages#home'

end

app/models/tipp_group.rb
class TippGroup < ActiveRecord::Base
  belongs_to :user
  has_many :group_members
  has_many :users, through: :group_members
  validates_presence_of :user_id, :name, :password
  validates_uniqueness_of :name

  scope :ordered, -> { order(:name) }
  validates :name, length: { in: 3..20 }
  validates :password, length: { in: 6..20 }

end

app/controllers/tipp_groups_controller.rb
class TippGroupsController < ApplicationController
  before_action :set_tipp_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /tipp_groups
  # GET /tipp_groups.json
  def index
    @tipp_groups = TippGroup.ordered
    @founded_groups = current_user.tipp_groups
    @member_groups = GroupMember.includes(:tipp_group).where(user_id: current_user.id)
  end

  # GET /tipp_groups/1
  # GET /tipp_groups/1.json
  def show
    @isFounder = authorize
  end

  # GET /tipp_groups/new
  def new
    @tipp_group = TippGroup.new
  end

  # GET /tipp_groups/1/edit
  def edit
    redirect_to @tipp_group unless authorize
  end

  # POST /tipp_groups
  # POST /tipp_groups.json
  def create
    @tipp_group = TippGroup.new(tipp_group_params)
    @tipp_group.user_id = current_user.id if current_user
    
    respond_to do |format|
      if @tipp_group.save
        format.html { redirect_to @tipp_group, notice: 'Tipp-Gruppe wurde erstellt!' }
        format.json { render :show, status: :created, location: @tipp_group }
      else
        format.html { render :new }
        format.json { render json: @tipp_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipp_groups/1
  # PATCH/PUT /tipp_groups/1.json
  def update
    if authorize
      respond_to do |format|
        if @tipp_group.update(tipp_group_params)
          format.html { redirect_to @tipp_group, notice: 'Tipp group was successfully updated.' }
          format.json { render :show, status: :ok, location: @tipp_group }
        else
          format.html { render :edit }
          format.json { render json: @tipp_group.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to @tipp_group
    end
  end

  # DELETE /tipp_groups/1
  # DELETE /tipp_groups/1.json
  def destroy
    if authorize
      @tipp_group.destroy 
      respond_to do |format|
        format.html { redirect_to tipp_groups_url, notice: "Tipp-Gruppe \"#{@tipp_group.name}\" wurde gelöscht." }
        format.json { head :no_content }
      end
    else
      redirect_to @tipp_group
    end
  end

  def create_member
    password = params[:password]
    id = params[:id]
    tipp_group = TippGroup.find(id)
    redirect_to tipp_group_path(id), notice: "Sie können nicht ihrer eigenen Gruppe beitreten." if current_user.id == tipp_group.user_id

    if tipp_group.password == password
      p new_member = GroupMember.new(user_id: current_user.id, tipp_group_id: id)
      if new_member.save
        redirect_to tipp_group_path(id), notice: "Sie wurden der Gruppe \"#{tipp_group.name}\" hinzugefügt."
      else
        redirect_to tipp_group_path(id), notice: "Sie gehören schon zur Gruppe \"#{tipp_group.name}\"."
      end
    else
      redirect_to tipp_group_path(id), notice: "Gruppenpasswort war nicht korrekt."
    end
  end

  def delete_member
    tipp_group_id = params[:id]
    tipp_group = TippGroup.find(tipp_group_id)
    user_id = params[:user]
    user = User.find(user_id)

    if current_user.id == tipp_group.user_id
      gm = GroupMember.where(user_id: user, tipp_group_id: tipp_group_id)
      GroupMember.destroy(gm)
      redirect_to tipp_group_path(tipp_group_id), notice: "Mitglied #{user.username} wurde aus der Gruppe \"#{tipp_group.name}\" entfernt."
    else
      redirect_to tipp_group_path(tipp_group_id), notice: "Sie haben keine Berechtigung Mitglieder aus dieser Gruppe zu entfernen."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipp_group
      @tipp_group = TippGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipp_group_params
      params.require(:tipp_group).permit(:user_id, :password, :name)
    end

    def authorize
      return false if current_user.id != @tipp_group.user_id
      true
    end
end

app/helpers/tipp_groups_helper.rb
module TippGroupsHelper
end

app/views/tipp_groups/_form.html.erb
<%= form_for(@tipp_group, html: {class: "", role: "form"}) do |f| %>
  <% if @tipp_group.errors.any? %>
    <div class="alert alert-danger">
      <% @tipp_group.errors.full_messages.each do |message| %>
        <%= message %><br>
      <% end %>
    </div>

  <% end %>
  <div class="form-group">
    <%= f.label :name, "Gruppenname" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :password, "Gruppen-Passwort" %><br>
    <%= f.text_field :password, class: "form-control"  %>
  </div>
  
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tipp_groups/edit.html.erb
<div class="col-md-8">
  <div class="well">
    <h1>Tipp-Gruppe bearbeiten</h1>

    <%= render 'form' %>

    <%= link_to 'Anzeigen', @tipp_group %> |
    <%= link_to 'Zurück', tipp_groups_path %>
  </div>
</div>

app/views/tipp_groups/index.html.erb
<div class="col-md-8">
  <div class="well">
    <% if flash[:notice] %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <h3>Alle Tipp-Gruppen</h3>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Gruppenname</th>
          <th>Gruppengründer</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @tipp_groups.each do |tipp_group| %>
          <tr>
            <td><%= tipp_group.name %></td>
            <td><%= tipp_group.user.username %></td>

            <td><%= link_to 'Mitglied werden', tipp_group, class: "btn btn-primary btn-sm active pull-right" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Neue Tipp-Gruppe erstellen', new_tipp_group_path, class: "btn btn-primary active" %>
  </div>
</div>
<div class="col-md-4">
  <div class="panel panel-primary">
    <div class="panel-heading"><b>Ihre Gruppen:</b></div>
    <table class="table">
      
      <tbody>
        <% @founded_groups.each do |group| %>
          <tr>
            <td><%= link_to group.name, group, class: "btn btn-primary btn-sm active" %></td>
            <td><%= link_to 'Rangliste', rankings_tipp_group_show_path(group), class: "btn btn-info btn-sm active pull-right" %></td>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div><div class="col-md-4">
  <div class="panel panel-primary">
    <div class="panel-heading"><b>Mitglied von:</b></div>
    <table class="table">
      
      <tbody>
        <% @member_groups.each do |group| %>
          <tr>
            <td><%= link_to group.tipp_group.name, group.tipp_group, class: "btn btn-primary btn-sm active" %></td>
            
            <td><%= link_to 'Rangliste', rankings_tipp_group_show_path(group.tipp_group), class: "btn btn-info btn-sm active pull-right" %></td>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tipp_groups/new.html.erb
<div class="col-md-8">
  <div class="well">
    <h3>Neue Tipp-Gruppe erstellen</h3>

    <%= render 'form' %>

    <%= link_to 'Zurück', tipp_groups_path %>
  </div>
</div>

app/views/tipp_groups/show.html.erb
<div class="col-md-6">
  <div class="well">
    <% if flash[:notice] %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <h4>
      <strong>Gruppenname:</strong>
      <%= @tipp_group.name %>
    </h4>
    <h4>
      <strong>Gründer der Gruppe:</strong>
      <%= @tipp_group.user.username %>
    </h4>

  
  
    <% if @isFounder %>
      <h4>
        <strong>Gruppen-Passwort:</strong>
        <%= @tipp_group.password %>
      </h4>
      <p>
        <%= link_to 'Gruppe bearbeiten', edit_tipp_group_path(@tipp_group), class:"btn btn-primary" %>
        <%= link_to 'Gruppe löschen', @tipp_group, method: :delete, data: { confirm: 'Sind Sie sicher?' }, class:"btn btn-danger pull-right" %>

      </p>
    <% else %>
      <button class="btn btn-primary" data-toggle="modal" data-target=".bs-join-group-modal-sm">Gruppe beitreten</button>
    <% end %>
   
    <div class="modal fade bs-join-group-modal-sm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Gruppe beitreten</h4>
          </div>
          <div class="modal-body">
            <%= form_tag(create_member_tipp_group_path, method: "post", class: "form-inline", role: "form") do %>
               <div class="form-group">    
              <%= hidden_field_tag 'id', @tipp_group.id %>
              <%= label_tag :password, "Passwort: " %>
              <%= text_field_tag :password, nil, class: "form-control" %>
              </div> 
              <%= submit_tag "Gruppe beitreten", class: "btn btn-primary"  %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <%= link_to 'Zurück', tipp_groups_path %>
  </div>
</div>
<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading"><b>Mitglieder der Gruppe:</b></div>
    <table class="table">
      
      <tbody>
        <% @tipp_group.users.each do |user| %>
          <tr>
         
            <td><%= user.username  %></td>
            <% if @isFounder %>
              <td><%= link_to 'Mitglied enfernen', delete_member_tipp_group_path(user: user.id), method: :delete, data: { confirm: 'Sind Sie sicher?' }, class:"btn btn-danger btn-sm pull-right" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>