config/routes.rb
Rails.application.routes.draw do
  
  resources :tipp_groups do
    member do
     post 'create_member'
     delete 'delete_member'
    end
  end
  get 'rankings/overall/:id', to: 'rankings#overall', as: :rankings_overall_show
  get 'rankings/tipp_group/:id', to: 'rankings#tipp_group', as: :rankings_tipp_group_show
  get 'rankings/matchday/:id', to: 'rankings#matchday', as: :rankings_matchday_show

  get 'regeln', to: 'static_pages#rules', as: :rules
  get 'home', to: 'static_pages#home', as: :home

  get 'tipps', to: 'tipps#index', as: :tipps_index
  get 'tipps/:id', to:'tipps#edit', as: :edit_tipp
  post 'tipps', to:'tipps#create', as: :tipps

  devise_for :users

  root 'static_pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bundesliga Tippspiel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="col-md-12">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">  
         <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>     
          <a class="navbar-brand" href="/">Bundesliga Tippspiel 2014/15</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Tippen", tipps_index_path %></li>
            <li><%= link_to "Rangliste", rankings_overall_show_path(1) %></li>
            <li><a href="/regeln">Regeln</a></li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
                  <div>
                    <span class="badge alert-info">
                      Platz: <%= current_user.rank %>
                      Punkte: <%= current_user.points %>
                    </span><%= "&nbsp;".html_safe %>
                    <span class="glyphicon glyphicon-user"> </span> 
                    <%= current_user.username %><span class="caret"></span>
                    
                  </div>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Profil ändern", edit_user_registration_path %></li>
                  <li><%= link_to "Tippgruppen", tipp_groups_path %></li>

                  <li class="divider"></li>
                  <li><%= link_to "Ausloggen", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
            <li><%= link_to "Einloggen", new_user_session_path %></li>
            <li><%= link_to "Registrieren", new_user_registration_path %></li>

            <% end %>
            
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>
  <%= yield %>

</div>

</body>
</html>